SRCS=$(wildcard test*.c)
PROGS=$(patsubst %.c,%,  $(SRCS))
OBJS =$(patsubst %.c,%.o,$(SRCS))

all: $(PROGS) tests

PROGS += perf

LDFLAGS=-L../src -lshr
CFLAGS = -I../src -I../lib
CFLAGS += -Wall -Wextra
CFLAGS += -g -O0
#CFLAGS += -O2

# static pattern rule: multiple targets 
$(OBJS): %.o: %.c
	$(CC) -c $(CFLAGS) $< 

# use libtool to link the test executables for ../src/libshr.so
$(PROGS): %: %.o
	../libtool --mode=link --tag=CC $(CC) -o $@ $(CFLAGS) $< $(LDFLAGS)

.PHONY: clean tests

tests:	
	perl ./do_tests

clean:	
	rm -f $(OBJS) $(PROGS) *.out *.ring 
